### ISSUE TITLE
'libcudart.so.11.0'; dlerror:

### ISSUE THREAD

**Issue by horizenight** [horizenight/DeepFinderModified#6]
This occurs due to integration of cuda.

Error Reproduce : when display script is run .

**Comment by horizenight** [comment]
I went to the [CUDA toolkit website](https://developer.nvidia.com/cuda-downloads), selected the options, and that showed some instructions like this:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda-repo-ubuntu2004-11-6-local_11.6.2-510.47.03-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2004-11-6-local_11.6.2-510.47.03-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu2004-11-6-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda         # I have broken packages, so could not invoke this command
```
So the instructions will change depending on your specifications, DO NOT copy from here/other stackoverflow answer.

I could not invoke the last command, but after some trials and errors, I invoked:
```
sudo apt install libcudart.so.11.0   # this worked for me!
```
This worked for me!

**Comment by horizenight** [comment]
Another fix:: 

```
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
python3 -m pip install tensorflow
# Verify install:
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

```
